M48
; DRILL file {KiCad (6.0.5)} date Sun Jul 24 11:35:22 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-24T11:35:22-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.000
%
G90
G05
T1
X136.5Y-76.0
X143.5Y-76.0
X150.0Y-76.0
X157.0Y-76.0
T0
M30
